### ISSUE TITLE
SQLCODE: -501 - Attempt to reclose a closed cursor

### ISSUE THREAD

**Issue by fdcastel** [pauldex/sqlalchemy-firebird#32]
**Describe the bug**

A simple Pandas `.read_sql()` fails after installing this package.

Without `sqlalchemy-firebird` installed, the code works with the following warning:

```
SADeprecationWarning: The firebird dialect is deprecated and will be removed in a future version. This dialect is superseded by the external dialect https://github.com/pauldex/sqlalchemy-firebird.
```

After installing `sqlalchemy-firebird` the code doesn't work anymore. Failing with

```
fdb.fbcore.DatabaseError: ('Error while releasing SQL statement handle:\n- SQLCODE: -501\n- Attempt to reclose a closed cursor', -501, 335544577)
```

**To Reproduce**

```python
basesSql = """
SELECT
  1 "IntField",
  'Some words' "TextField",
  CURRENT_TIMESTAMP "UpdatedAt"
FROM
  mon$database
"""

fbEngine = sqlalchemy.create_engine('firebird://...')

with fbEngine.connect() as fbConn:
    bases = pd.read_sql(basesSql, fbConn)

```

**Expected behavior**

Pandas `.read_sql()` executed successfully.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19042.1083
 - Python 3.9.6
 - Firebird 3.0.7
 - All pip packages installed with the latest release version

```
fdb==2.0.1
firebird-base==1.3.0
firebird-driver==1.2.1
future==0.18.2
greenlet==1.1.0
numpy==1.21.0
pandas==1.3.0
petl==1.7.4
protobuf==3.17.3
psycopg2==2.9.1
python-dateutil==2.8.1
pytz==2021.1
six==1.16.0
SQLAlchemy==1.4.20
sqlalchemy-firebird==0.7.0
```

**Comment by fdcastel** [comment]
Output of `pd.read_sql()` call:

```
Error closing cursor
Traceback (most recent call last):
  File "c:\Temp\pysync2\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "c:\Temp\pysync2\.venv\lib\site-packages\sqlalchemy_firebird\kinterbasdb.py", line 117, in do_execute
    cursor.execute(statement, parameters or [])
  File "c:\Temp\pysync2\.venv\lib\site-packages\fdb\fbcore.py", line 3689, in execute
    self._ps._execute(parameters)
  File "c:\Temp\pysync2\.venv\lib\site-packages\fdb\fbcore.py", line 3361, in _execute
    self.__tuple2xsqlda(self._in_sqlda, parameters)
  File "c:\Temp\pysync2\.venv\lib\site-packages\fdb\fbcore.py", line 3142, in __tuple2xsqlda
    raise ValueError("Value of parameter (%i) is too long,"
ValueError: Value of parameter (0) is too long, expected 93, found 270

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Temp\pysync2\.venv\lib\site-packages\sqlalchemy\engine\base.py", line 1865, in _safe_close_cursor
    cursor.close()
  File "c:\Temp\pysync2\.venv\lib\site-packages\fdb\fbcore.py", line 3646, in close
    self._ps.close()
  File "c:\Temp\pysync2\.venv\lib\site-packages\fdb\fbcore.py", line 3467, in close
    self._free_handle()
  File "c:\Temp\pysync2\.venv\lib\site-packages\fdb\fbcore.py", line 3324, in _free_handle
    raise exception_from_status(DatabaseError, self._isc_status,
fdb.fbcore.DatabaseError: ('Error while releasing SQL statement handle:\n- SQLCODE: -501\n- Attempt to reclose a closed cursor', -501, 335544577)
```

**Comment by fdcastel** [comment]
Updated original message with a `SELECT` query from `MON$DATABASE` which reproduces the problem.

**Comment by fdcastel** [comment]
After uninstalling the package with

```
pip uninstall sqlalchemy-firebird
``` 

the `.read_sql()` call works correctly.

**Comment by pauldex** [comment]
Thanks for reporting this issue.  I will investigate why this happens.

**Comment by fdcastel** [comment]
@pauldex, sorry to chime in but had you got the chance to look over this one?

**Comment by gordthompson** [comment]
FWIW, I am unable to reproduce your issue:

```python
import fdb
import pandas as pd
import sqlalchemy as sa

# Firebird version 3.0.2 from Ubuntu 18.04 repo
# sqlalchemy-firebird from current master branch

print(pd.__version__)  # 1.1.5
print(sa.__version__)  # 1.4.25
print(fdb.__version__)  # 2.0.1

fbEngine = sa.create_engine(
    "firebird://sysdba:scott_tiger@localhost//home/gord/Databases/sandbox.fdb?charset=UTF8",
    echo=True,
)

basesSql = """
SELECT
  1 "IntField",
  'Some words' "TextField",
  CURRENT_TIMESTAMP "UpdatedAt"
FROM
  mon$database
"""

with fbEngine.connect() as fbConn:
    bases = pd.read_sql(basesSql, fbConn)
    print(bases)
    """
       IntField   TextField               UpdatedAt
    0         1  Some words 2021-09-27 11:37:04.851
    """
```

**Comment by fdcastel** [comment]
Thank you @gordthompson for the sample. It is indeed working now!

Unfortunately I don't know what has been changed since my original post. I've been using the old (deprecated) dialect since then.

However, when using `sqlalchemy-firebird` now I got a warning and a `ReferenceError: weakly-referenced object no longer exists` exception (ignored):

```
1.3.0
1.4.25
2.0.1
2021-09-27 16:54:09,109 INFO sqlalchemy.engine.Engine
            SELECT 1 AS has_table FROM rdb$database
            WHERE EXISTS (SELECT rdb$relation_name
                          FROM rdb$relations
                          WHERE rdb$relation_name=?)

2021-09-27 16:54:09,109 INFO sqlalchemy.engine.Engine [dialect firebird+fdb does not support caching 0.00024s] ('\nSELECT\n  1 "IntField",\n  \'Some words\' "TextField",\n  CURRENT_TIMESTAMP "UpdatedAt"\nFROM\n  mon$database\n',)
2021-09-27 16:54:09,109 INFO sqlalchemy.engine.Engine ROLLBACK
2021-09-27 16:54:09,109 INFO sqlalchemy.engine.Engine
SELECT
  1 "IntField",
  'Some words' "TextField",
  CURRENT_TIMESTAMP "UpdatedAt"
FROM
  mon$database

2021-09-27 16:54:09,109 INFO sqlalchemy.engine.Engine [raw sql] ()
Exception ignored in: <function PreparedStatement.__del__ at 0x000001D7DA761F70>
Traceback (most recent call last):
  File "C:\Temp\TstPandas\env\lib\site-packages\fdb\fbcore.py", line 3462, in __del__
    self._close()
  File "C:\Temp\TstPandas\env\lib\site-packages\fdb\fbcore.py", line 3338, in _close
    if is_dead_proxy(self.cursor):
  File "C:\Temp\TstPandas\env\lib\site-packages\fdb\fbcore.py", line 481, in is_dead_proxy
    return isinstance(obj, weakref.ProxyType) and not dir(obj)
ReferenceError: weakly-referenced object no longer exists
   IntField   TextField               UpdatedAt
0         1  Some words 2021-09-27 16:54:09.109
```

Did this problems occur in your tests?



Without `sqlalchemy-firebird` installed this doesn't happen. And the only warning is the one about the old dialect being deprecated:

```
1.3.0
1.4.25
2.0.1
C:\Temp\TstPandas\test.py:12: SADeprecationWarning: The firebird dialect is deprecated and will be removed in a future version. This dialect is superseded by the external dialect https://github.com/pauldex/sqlalchemy-firebird.
  fbEngine = sa.create_engine(
2021-09-27 16:53:50,843 INFO sqlalchemy.engine.Engine
SELECT
  1 "IntField",
  'Some words' "TextField",
  CURRENT_TIMESTAMP "UpdatedAt"
FROM
  mon$database

2021-09-27 16:53:50,843 INFO sqlalchemy.engine.Engine [raw sql] ()
   IntField   TextField               UpdatedAt
0         1  Some words 2021-09-27 16:53:50.843
```

**Comment by gordthompson** [comment]
I didn't get the `ReferenceError` warning with Python 3.6 (default version for Ubuntu 18.04) but I did get it after upgrading to Python 3.9. It seems to be related to using `.read_sql()` because it went away when I used `.read_sql_query()` instead.

**Comment by fdcastel** [comment]
Nice catch! I will open a new issue about this.

Thank you @gordthompson !!
